- package.json
> Update name 0

- server/api/index.js
- server/api/trips.js
> trip_routes_1

- server/api/trips.js
> #5 express trip route find by id

- package-lock.json
- server/api/trips.spec.js
- server/db/models/category.js
- server/db/models/trips.spec.js
> #32 trip test spec setup

- client/app.js
- client/components/trips.js
- client/store/trips.js
> basic(ugly) rendering of basic data for each trip in trip component

- client/app.js
- client/components/singleTrip.js
- client/components/user-home.js
- client/store/index.js
- client/store/trips.js
> Single product#9

- client/app.js
- client/components/trips.js
- client/routes.js
- package-lock.json
> added a route to /trips

- client/components/singleTrip.js
- client/routes.js
- client/store/trips.js
> SingleTripRouting added

- client/app.js
- client/components/sidebar.js
- client/store/categories.js
- client/store/index.js
- client/store/trips.js
- server/api/categories.js
- server/api/index.js
> Filter by category

- client/components/singleTrip.js
- script/seed.js
- server/db/models/trips.js
> added base seed file

- client/components/navbar.js
> #15 top nav bar

- client/components/trips.js
> added links to single pages

- client/components/navbar.js
> Failed prop type error fix

- client/app.js
- client/components/addNewTrip.js
- client/routes.js
- client/store/trips.js
- server/api/trips.js
> Product form component#28

- script/seed.js
- server/db/models/trips.js
> fixed images

- client/components/home.js
> homepage fix

- client/components/sidebar.js
- client/components/trips.js
- client/routes.js
- public/style.css
> images orginised

- client/components/home.js
> homepage styling fixes

- client/store/trips.js
- server/db/models/trips.js
> adjustments to trips

- client/components/singleTrip.js
> added description to single trip

- client/components/navbar.js
- client/routes.js
> Modifying trip model

- client/components/sidebar.js
- public/style.css
> fixed sidebar

- client/routes.js
> added route back in

- client/components/addNewTrip.js
- client/components/trips.js
- client/routes.js
- client/store/index.js
- client/store/trips.js
- doc/cart.md
- server/api/trips.spec.js
- server/db/models/trips.js
- server/index.js
> ashi notes and code review changes

- client/app.js
- client/components/sidebar.js
- client/components/trips.js
- public/style.css
> trips page has sidebar

- client/components/navbar.js
- server/db/models/user.js
> isAdmin selective rendering in navbar

- client/components/addNewTrip.js
- client/components/editTrip.js
- client/components/singleTrip.js
- client/components/user-home.js
- client/routes.js
> edit form rendering in single page when user logged in as admin

- client/components/singleTrip.js
- server/api/index.js
- server/api/orders.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/tripOrder.js
> Order model

- client/routes.js
- server/api/orders.js
> Order getall route

- client/components/home.js
- server/index.js
> #19 homepage

- client/components/cart.js
- client/components/singleTrip.js
- client/store/cart.js
- client/store/trips.js
- server/api/orders.js
> working on cart view

- client/components/home.js
- client/index.scss
- doc/scssClasses
- public/index.html
> bootstrap homepage top

- client/components/navbar.js
> Fixing navbar functionality

- client/components/cart.js
- client/components/singleTrip.js
- package-lock.json
- package.json
- server/api/orders.js
- server/db/models/cart.js
- server/db/models/index.js
- server/db/models/order.js
- server/index.js
> Posting cart with join

- client/components/home.js
- client/components/trips.js
> linking single trips

- script/seed.js
> seed data for TripCategory

- client/components/cart.js
- client/components/home.js
- package-lock.json
- public/style.css
> added total and minor changes on cart and front page

- client/components/cart.js
- client/components/navbar.js
- client/components/singleTrip.js
- client/store/cart.js
- server/api/cart.js
- server/api/index.js
- server/api/orders.js
- server/db/models/cart.js
- server/db/models/index.js
- server/db/models/order.js
> Changing models

- client/components/addNewTrip.js
- client/components/cart.js
- client/components/editTrip.js
- client/components/singleTrip.js
- client/components/trips.js
- client/store/categories.js
- client/store/trips.js
- server/db/models/trips.js
> deleted lots of console.logs!

- server/api/orders.js
> now includes backend authorization for getAll route for orders

- client/store/index.js
- package-lock.json
- server/api/index.js
> fixed some reference errors

- client/components/cart.js
- client/components/checkout.js
- client/routes.js
- server/api/checkout.js
- server/api/orders.js
- server/index.js
> stripe checkout working!

- client/components/auth-form.js
- client/components/home.js
- client/components/sidebar.js
- client/components/trips.js
- public/style.css
> minor pages update

- client/components/cart.js
- client/store/cart.js
- client/store/trips.js
> can delete a line item in cart

- client/components/cart.js
- server/api/orders.js
> deleting bind
